### ISSUE TITLE
fia to level3a conversion for Atlantic white cedar is wrong

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/FIA_products#1]
@jpeters7 we have Atlantic white cedar converted to cedar/juniper in fia_level3a_conversion_v0.2.csv, but Atlantic white cedar is a PalEON level 3a taxon. Could you fix this and update the Wiki?

Note, there's no code in this repo yet but I'll put it in soon. So don't be surprised by things looking vacant at the moment.

**Comment by jpeters7** [comment]
@paciorek - sorry for the delay with this...  The fia_level3a_conversion is now at version 0.4 and the Atlantic white cedar gets converted to Atlantic white cedar. You can get the updated file on the wiki here: https://paleon.geography.wisc.edu/doku.php/data_and_products;taxatranslation.
The file name is: fia_to_level3a_v0.4.csv
